### ISSUE TITLE
Can't configure the HLF client

### ISSUE THREAD

**Issue by cenyuzhang** [IBM/securitization_blockchain#2]
After filling out the blockchain credentials correctly, and tried to connect to the HLF client, nothing happened. Didn't see anything in the log.

**Comment by kkbankol-ibm** [comment]
Hello @cenyuzhang , are you using a local hyperledger network, or are you using a hosted IBM Blockchain service? 
If you're using the hosted service, can you check in the `sc-ui` directory and see if there is a `connection_profile.json` and `monitoring_admin` file?

**Comment by cenyuzhang** [comment]
@kkbankol-ibm I am using the IBM hosted service. I don't have any connection_profile.json or monitoring_admin file in the sc-ui directory. Could you let me know the instruction on how and where to add them? Thanks!

**Comment by kkbankol-ibm** [comment]
Hello @cenyuzhang , I've just pushed a few updates, can you pull those down and try again? Also, are you running the web application on your local machine, or is that being hosted by bluemix as well

**Comment by cenyuzhang** [comment]
@kkbankol-ibm thanks. I will try that and let you know. I tried both the web app on bluemix and local machine.

**Comment by cenyuzhang** [comment]
@kkbankol-ibm it's resolved. thanks!
